### PR TITLE
No more array_get() calls

### PR DESCRIPTION
**Pull request by xbill82**

### CODE REVIEW

**Comment by tobscure** [comment]
Thanks for the PR, this won't work in some cases though: `getRelationshipFromMethod` may return a falsey value, in which case calling `$method` will fail. Needs to be:

```php
$method = $this->getRelationshipFromMethod($name);

if ($method) {
    $element = $method( // .. and so on
```

**Comment by xbill82** [comment]
Ah yes, you're right!
Sorry, is there an easy way to amend the PR without discarding this one?

**Comment by tobscure** [comment]
You can push to the same branch and then squash the commits, I think

**Comment by xbill82** [comment]
Ok I've pushed the new commit, what does *squash* mean?

**Comment by xbill82** [comment]
Ok I guess I have squashed them

**Pull request merged**
