### PR TITLE
Moving JSON API handlers in from flarum/core

### PR DESCRIPTION
**Pull request by kirkbushell**

### CODE REVIEW

**Comment by tobscure** [comment]
Looks good, one last thing: could you please squash the commits?

**Comment by kirkbushell** [comment]
Is that really necessary?

**Comment by tobscure** [comment]
Just to keep things nice and tidy. http://programmers.stackexchange.com/a/263172

**Comment by kirkbushell** [comment]
How do you squash? I just tried based on this: http://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git

And all it did was add 2 more commits =\

**Comment by tobscure** [comment]
Hmm, maybe try this? http://eli.thegreenplace.net/2014/02/19/squashing-github-pull-requests-into-a-single-commit

**Comment by kirkbushell** [comment]
That assumes a feature branch, which I don't have. Any other ideas?

I've spent more time trying to squash the commit than I have doing the actual work.

**Pull request closed without merging**
