### PR TITLE
Add badges

### PR DESCRIPTION
**Pull request by vinkla**

### CODE REVIEW

**Comment by vinkla** [comment]
:+1:

**Comment by vinkla** [comment]
Only thing left is to get it up to speed with the latest changes in the standard for the 1.0 version.

**Comment by tobscure** [comment]
Yep. I'm not quite sure exactly what the changes are – it already puts attributes in a sub-array which I think was introduced in RC4. Can't imagine there's anything too major we're missing, if anything at all.

That and write some more tests :D

**Comment by vinkla** [comment]
We need to add support for fields http://jsonapi.org/format/#document-resource-object-fields Other than that I dunno. We should probably double check the format just to be sure we've everything in.

**Pull request merged**
