### PR TITLE
Test agains 5.5.9

### PR DESCRIPTION
**Pull request by vinkla**
Since we target 5.5.9 we could/should also test against it.

### CODE REVIEW

**Comment by tobscure** [comment]
Lol I literally just released 0.3.0! But thanks :)

**Comment by tobscure** [comment]
wait, why do we target 5.5.9 in the first place?

**Comment by vinkla** [comment]
Since there is a lot of bugfixes in that release. I've been told earlier versions are just as bad as using 5.4

**Comment by vinkla** [comment]
This is the version used by both Laravel and Symfony. I guess we can bump it to 5.6.4 later this year when 5.5 goes EOL.

**Pull request merged**
