### PR TITLE
Add Changelog for 0.1.0

### PR DESCRIPTION
**Pull request by vinkla**
Please release this first testing version `0.1.0`. When this release is tagged we can start testing this is real environments and don't have to rely on `dev-master` to be stable.

### CODE REVIEW

**Comment by vinkla** [comment]
@tobscure Let me know when we can release a new version and I'll fix the date asap.

**Comment by tobscure** [comment]
Sorry for the delay. If you can bump the date then I'll merge :)

**Comment by vinkla** [comment]
No worries! Just glad to get this tagged :+1: I've updated the date now.

**Comment by tobscure** [comment]
Tagged!

**Comment by vinkla** [comment]
awesome

**Pull request merged**
